name: FiveMinutesRule
main: org.bitterorange.fiveminutesrule.FiveMinutesRule
api-version: 1.13

version: 1.1
author: BitterOrange

commands:
  fmr:
    description: FiveMinutesRule Commands
    usage: |
      /fmr